linters:
  enable-all: true
  disable:
    - testpackage
    - goerr113
    - gochecknoglobals
    - gochecknoinits
    - godot
    - godox
    - wsl
    - gomnd
    - lll
linters-settings:
  errcheck:
    check-type-assertions: true
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
        - scopelint
